### ISSUE TITLE
Error on License creation

### ISSUE THREAD

**Issue by ricardobrg** [tiki/tiki-sdk-js#128]
When trying to create a License manually, this error is thrown:

```
index.js:1 Uncaught TypeError: e.charCodeAt is not a function
    at hp.T (index.js:1:167469)
    at zl.pr (index.js:1:217161)
    at xq.E (index.js:1:216725)
    at db.bV (index.js:1:563289)
    at index.js:1:564855
    at G.a (index.js:1:42343)
    at zE.$2 (index.js:1:188691)
    at Object.E (index.js:1:42060)
    at um.rQ (index.js:1:565025)
    at um.ct (index.js:1:564623)
```
I tried to debug in the transpiled code but didn't have any success. Need to check in the source code with the same parameters.

The title object created returns without origin. Other than that it looks regular:

```
{
    "id": "xGjMMbM0nyJ6qUifCWe70-zmCZkAEIIWg7-VyfZwt4k",
    "hashedPtr": "MFR2KwqLMa3+ee+zvHcYYkYnzJnHyPOb+lkc5oVKwF0=",
    "tags": [
        {
            "_value": "custom:device_id"
        }
    ],
    "origin": "",
    "description": ""
}
````

### Steps to reproduce
Open this sample HTML page in a browser. After the Title is created the error is thrown.

```
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <script src="https://unpkg.com/@mytiki/tiki-sdk-js@2.1.3/dist/index.js"></script>
    </head>

    <body>
        <script>
            (async () => {
                debugger
                await TikiSdk.config()
                    .offer
                    .description("offer_desc")
                    .bullet({ text: "1", isUsed: true })
                    .bullet({ text: "2", isUsed: true })
                    .bullet({ text: "3", isUsed: false })
                    .tag(TikiSdk.Trail.Title.TitleTag.deviceId())
                    .use({ usecases: [TikiSdk.Trail.License.LicenseUsecase.attribution()] })
                    .terms("")
                    .ptr("test123")
                    .add()
                    .initialize("6c1f61cf-ab35-4020-b852-a7baf9ec8fdb", "cust23")
                let offer = TikiSdk.config()._offers[0]
                let title = await TikiSdk.Trail.Title.getByPtr(offer._ptr)
                if (!title) {
                    title = await TikiSdk.Trail.Title.create(
                        offer._ptr,
                        offer._tags,
                        "desc"
                    )
                }
                console.log(title)
                let license = await TikiSdk.Trail.License.create(
                    title.id,
                    offer._uses,
                    offer._terms,
                    offer._description,
                    offer._expiry
                )   
                console.log(license)
                const payable = await TikiSdk.Trail.Payable.create(
                    license.id,
                    "10",
                    "percent off",
                    "test payable",
                    new Date(),
                    "tid"
                )
                console.log(payable)
                const receipt = await TikiSdk.Trail.Receipt.create(
                    payable.id,
                    "10",
                    "order number 123",
                    "gid://order/123"
                )
                console.log(receipt)
            })()
        </script>
    </body>

</html>
```

**Comment by ricardobrg** [comment]
@mike-audi do you have any idea what might be causing this error?

**Comment by ricardobrg** [comment]
The terms need to be passed as string. The Offer.terms is an object.
